"""Hand-drawn 28px hero glyphs — IN-SOURCE bitmaps, no asset files.

WHY IN-SOURCE rather than a committed PNG sprite or a TTF:
  * a wrong pixel is caught in CODE REVIEW, not by opening an image viewer;
  * it keeps the draw layer free of any asset-loading path, which could behave differently
    on the Pi than on the Mac — exactly the divergence that made us reject a system font
    and is the whole reason golden-image tests are meaningful here.

THE ALPHABET IS 13 GLYPHS: 0-9 plus `.` `k` `-`. Bounded on purpose and asserted by test
(`test_glyph_set_is_bounded` in the spec tests): `k` carries the >=10,000 ft overflow form
(`10.2k`), and the MINUS IS LOAD-BEARING — F1's own pad baseline was -84 ft, so a negative
AGL hero is a real case, not a hypothetical.

Each glyph is a list of strings, one per row, `#` = lit. Height is HERO_H for every glyph so
rows align; width varies per glyph and the renderer chooses monospace or proportional
advance. Strokes are 4px so the digits stay solid at arm's length on a 128x64 panel.
"""

HERO_H = 28          # cap height, matching Option A's 28px hero band
STROKE = 4           # nominal stroke weight, in pixels

# 18 wide x 28 tall, 4px strokes. Drawn to read at ~1 m in daylight: closed counters kept
# generous so 8/0/6/9 do not fill in, and 1 has a foot so it cannot be mistaken for a stray
# stroke at a glance.
_D = {
    "0": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    "1": ["      ####    ",
          "     #####    ",
          "    ######    ",
          "   #######    ",
          "  ########    ",
          "  ### ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "      ####    ",
          "##############",
          "##############"],
    "2": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "         #### ",
          "        ####  ",
          "       ####   ",
          "      ####    ",
          "     ####     ",
          "    ####      ",
          "   ####       ",
          "  ####        ",
          " ####         ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "##############",
          "##############"],
    "3": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "     #########",
          "     #########",
          "     #########",
          "     #########",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    "4": ["####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "##############",
          "##############",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####"],
    "5": ["##############",
          "##############",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "############# ",
          "##############",
          "          ####",     # right stem only below the bar (was a stray left stem)
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    "6": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "############# ",
          "##############",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    "7": ["##############",
          "##############",
          "          ####",
          "          ####",
          "          ####",
          "         #### ",
          "         #### ",
          "        ####  ",
          "        ####  ",
          "       ####   ",
          "       ####   ",
          "      ####    ",
          "      ####    ",
          "     ####     ",
          "     ####     ",
          "    ####      ",
          "    ####      ",
          "   ####       ",
          "   ####       ",
          "  ####        ",
          "  ####        ",
          " ####         ",
          " ####         ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          "],
    "8": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          " ############ ",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    "9": ["  ##########  ",
          " ############ ",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "##############",
          " #############",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "          ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          " ############ ",
          "  ##########  "],
    # Narrow glyphs: the renderer may give these a tighter advance even in "monospace",
    # because a full-width dot or minus wastes the hero band's most precious resource.
    ".": ["    ",
          "    ", "    ", "    ", "    ", "    ", "    ", "    ",
          "    ", "    ", "    ", "    ", "    ", "    ", "    ",
          "    ", "    ", "    ", "    ", "    ", "    ", "    ",
          "    ",
          "####",
          "####",
          "####",
          "####",
          "####"],
    "-": ["          ",
          "          ", "          ", "          ", "          ",
          "          ", "          ", "          ", "          ",
          "          ", "          ",
          "##########",
          "##########",
          "##########",
          "##########",
          "          ", "          ", "          ", "          ",
          "          ", "          ", "          ", "          ",
          "          ", "          ", "          ", "          ",
          "          "],
    "k": ["####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####          ",
          "####      ####",     # 4px arms throughout — tapered arms vanished at arm's length
          "####      ####",
          "####    ####  ",
          "####    ####  ",
          "####  ####    ",
          "####  ####    ",
          "##########    ",
          "##########    ",
          "####  ####    ",
          "####  ####    ",
          "####    ####  ",
          "####    ####  ",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####",
          "####      ####"],
}

GLYPHS = dict(_D)
ALPHABET = "0123456789.k-"


def glyph(ch):
    """Rows for one glyph. KeyError is deliberate — the alphabet is bounded and closed, so
    an unexpected character is a bug in format_hero(), not something to paper over with a
    blank box."""
    return GLYPHS[ch]


def glyph_size(ch):
    rows = glyph(ch)
    return len(rows[0]), len(rows)


def advance(ch, monospace=True, cell=None, tracking=2):
    """Horizontal advance for one glyph.

    MONOSPACE keeps every digit in a fixed cell so the hero does not JITTER as digits change
    — at arm's length a number that shifts sideways every second reads as motion, and motion
    is the display's alarm channel. `.` and `-` still get their natural width: a full-width
    dot wastes the hero band's scarcest resource for no legibility gain.
    """
    w, _ = glyph_size(ch)
    if not monospace or ch in ".-":
        return w + tracking
    return (cell or max(glyph_size(c)[0] for c in "0123456789")) + tracking


def text_width(s, monospace=True, tracking=2):
    cell = max(glyph_size(c)[0] for c in "0123456789")
    return sum(advance(c, monospace, cell, tracking) for c in s)
